name: airbag
on:
  push:
    branches: 
      - master
  pull_request:
    branches:
      - master

jobs:
  unitTests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'
      - name: Unit Test
        run: dotnet test UnitTests
  buildImage:
    runs-on: ubuntu-latest
    needs:
      - unitTests
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker Image
        uses: actions/build-push-action@v1
        with:
          file: deployment/Dockerfile
      - name: Build Sample-auth Docker
        uses: docker/build-push-action@v2
        with:
          file: deployment/SampleAuthServer-Dockerfile
      
    